### ISSUE TITLE
TOC Candidate Nomination for Jan von Loewenstein

### ISSUE THREAD

**Issue by domdom82** [cloudfoundry/community#102]
Candidate Name: Jan von Loewenstein (SAP)

Nomination Statement: Jan is a very active member in the work around CF-for-K8S and Cloud-native Buildpacks.

**Comment by chipchilders** [comment]
@domdom82 can you add a reason that this was closed? Should we consider it a nomination, or should we consider the closing of the issue as meaning that you wanted to withdraw the nomination?

**Comment by domdom82** [comment]
@chipchilders I would like to withdraw. SAP have not yet decided on a candidate.

**Comment by bkrannich** [comment]
@domdom82: Thanks for your patience ;-) See #130 (as well as #129, #131).
