### ISSUE TITLE
Request to be an elector for TOC election

### ISSUE THREAD

**Issue by svkrieger** [cloudfoundry/community#112]
Github Username: svkrieger

Affiliation: SAP

Community participation:
https://github.com/cloudfoundry/cloud_controller_ng/pull/1973
https://github.com/cloudfoundry/cloud_controller_ng/pull/2079
https://github.com/cloudfoundry/cloud_controller_ng/pull/2163

**Comment by chipchilders** [comment]
@svkrieger what's your name, so that we can list you correctly. Thanks!

**Comment by chipchilders** [comment]
@svkrieger ping...

**Comment by svkrieger** [comment]
Sorry, public holiday here.
My name is Sven Krieger. Thanks for adding!
