### ISSUE TITLE
TOC principles: transparency and clarity are synonymous

### ISSUE THREAD

**Issue by emalm** [cloudfoundry/community#122]
According to Webster's (thesaurus, anyway), "[transparency](https://www.merriam-webster.com/thesaurus/transparency)" and "[clarity](https://www.merriam-webster.com/thesaurus/clarity)" are synonyms. I think it would make sense to consolidate the ["Clarity" section](https://github.com/cloudfoundry/community/blob/main/toc/PRINCIPLES.md#clarity) into the ["Transparency" one](https://github.com/cloudfoundry/community/blob/main/toc/PRINCIPLES.md#transparency) while still making sure to cover all the areas in which we want the community governance and activity to be transparent.

**Comment by emalm** [comment]
Also, it'd be nice still to have [3 principles](https://en.wikipedia.org/wiki/Hendiatris). Maybe "fairness" or "equality" would be a candidate quality? Something to represent the intent that if you show up and regularly do good work in the community, you'll garner additional authority and responsibility within the governance structure. I see that quality as being distinct from inclusivity, as the latter addresses increasing opportunities for contribution of work.

**Comment by loewenstein** [comment]
What I have always liked about the CF community was the _kindness_ that basically everyone was showing.

**Comment by emalm** [comment]
Ooh, yeah, "kindness" or a related synonym could be a good principle or value to incorporate here.
