### ISSUE TITLE
TOC Candidate Nomination for Eric Malm

### ISSUE THREAD

**Issue by emalm** [cloudfoundry/community#126]
Candidate Name: Eric Malm

Affiliation: VMware

Nomination Statement: I have considered it a tremendous privilege to build great software with the CF community over the past 7+ years, and I look forward to helping to make our community healthier and more diverse on top of more transparent, inclusive, and fair processes. I'm excited about the opportunities we have both to continue investment in the powerful systems we have built on top of BOSH and the CF App Runtime and to extend the value proposition of CF deeply into the Kubernetes community.

I have contributed significantly to the community discussions to define the TOC and working group roles over the past six months, in addition to carrying out my role as the App Runtime PMC lead in the previous governance structure. I also have broad knowledge across many CF projects, including not only the CF App Runtime but also BOSH, OSBAPI, and Paketo buildpacks, and would appreciate the chance to employ that context in service of our community.

**Comment by chipchilders** [comment]
Acknowledged and confirmed to meet TOC nominee criteria.
