### ISSUE TITLE
TOC Candidate Nomination for Andrew Edgar

### ISSUE THREAD

**Issue by cswanson2** [cloudfoundry/community#127]
Candidate Name: Andrew Edgar

Affiliation: IBM

Nomination Statement: Andrew has worked with Cloud Foundry (CF) for a long time, especially as a core contributor on the Diego development team as it became the default runtime.   In the past 8 years working on the IBM Public CF implementation, he has a wealth of hands-on experience of both customers using CF and the challenges and experience running a large CF installation.  He has developed and submitted many PRs in a wide variety of projects to improve how CF works and how it's managed and run.   He also was one of the first members of the Eirini development team as it began its incubation.   Recently he has been working on how to migrate IBMs large public VM based installation into a deployment based on Kubecf.  This development project involves working with the quarks and Kubecf teams testing, validating and submitting improvements to enable Kubecf to work in a large multi-tenant environment as well as designing how to enable a hybrid solution where migration from VMs can be done with zero downtime.   Andrew's main goal is to see Cloud Foundry continue to drive the user experience into Kubernetes.

**Comment by chipchilders** [comment]
Acknowledged and confirmed to meet TOC nominee criteria.

**Comment by andrew-edgar** [comment]
I accept this nomination.  Just to make it official :)
