### ISSUE TITLE
TOC Candidate Nomination for Beyhan Veli

### ISSUE THREAD

**Issue by bkrannich** [cloudfoundry/community#129]
Candidate Name: Beyhan Veli (@beyhan)

Affiliation: SAP

Nomination Statement:
Beyhan has been active in the Cloud Foundry community for the past 6+ years. He started as a contributor to Cloud Foundry as member of the BOSH team at SAP. Over time, he created 80+ pull requests and supported many more that the team initiated.

His focus areas have been BOSH in general, BOSH DNS, BOSH monitoring, the BOSH command line interface, and bosh-deployment. Additionally, he actively helped people via the community BOSH slack channel and gave sessions about BOSH at CF Summit and CF Operators SIG . E.g. in 2020, he did a CF summit session titled "A Journey Through BOSH and BOSH DNS Monitoring" (<https://sched.co/fDVn>, <https://youtu.be/jpnMKWKFhT0>).

More recently, Beyhan has taken on a broader role and is now also looking into other areas of Cloud Foundry like the Cloud Controller and general topics from a Cloud Foundry developer experience perspective.

Currently, Beyhan is a co-chair for the CF Summit 2021 "Behind the Curtain" track.

**Comment by chipchilders** [comment]
Acknowledged and confirmed to meet TOC nominee criteria.
