### ISSUE TITLE
TOC Candidate Nomination for Jan von Loewenstein

### ISSUE THREAD

**Issue by bkrannich** [cloudfoundry/community#130]
Candidate Name: Jan von Loewenstein (@loewenstein)

Affiliation: SAP

Nomination Statement:
Jan has been active in the Cloud Foundry community for the past 6+ years. He started as a contributor to Cloud Foundry as member of the BOSH team at SAP. Over time, he authored 30+ pull requests and helped in working on many more done by the SAP BOSH team.

When Cloud Foundry on Kubernetes became a thing, Jan built a prototypical BOSH CPI for Kubernetes (<https://youtu.be/xGwwyut-Yoo>, <https://github.com/SAP/bosh-kubernetes-cpi-release>). Additionally, he worked with the kubecf team, the Eirini team and later the cf-for-k8s teams. Most recently, he has taken on a broader role at SAP which extended his areas of focus also to the topic of Cloud Foundry application staging and buildpacks.

In the last months, Jan was an active part of the cross-company team that defined the new Cloud Foundry contribution guidelines in this repository which eventually led to this first TOC election.

**Comment by chipchilders** [comment]
Acknowledged and confirmed to meet TOC nominee criteria.
