### ISSUE TITLE
TOC Candidate Nomination for Stephan Merker

### ISSUE THREAD

**Issue by bkrannich** [cloudfoundry/community#131]
Candidate Name: Stephan Merker (@stephanme)

Affiliation: SAP

Nomination Statement:
Stephan has been active in the Cloud Foundry community for the past 6+ years. He is very active in Github issues, Slack conversations and has been contributing pull requests to Cloud Foundry.

He has been looking into and trouble-shooting issues with Cloud Foundry at scale in areas like Cloud Controller/CAPI, Diego, Loggregator, observability and monitoring of both Cloud Foundry itself as well as Cloud Foundry applications, cf-deployment, blobstore integration, Concourse, documentation and many more.

With his broad areas of expertise, Stephan is probably one of the people who has the broadest view on how Cloud Foundry is operated and being used by developers productively as he is the product owner of one of the SAP teams responsible for operating some of the biggest Cloud Foundry deployments world-wide on a broad set of IaaS infrastructures.

**Comment by chipchilders** [comment]
Acknowledged and confirmed to meet TOC nominee criteria.
