### ISSUE TITLE
TOC Candidate Nomination for Ruben Koster

### ISSUE THREAD

**Issue by dsboulder** [cloudfoundry/community#287]
Candidate Name: Ruben Koster @rkoster 

Affiliation: VMWare

Nomination Statement: Ruben has been a fantastic community player and contributor across many organizations. He's essentially playing a supporting member of the TOC right now, helping us do a lot of technology behind setting up working groups and teams. He's a natural leader, willing to make difficult decisions and move forward when needed.

**Comment by emalm** [comment]
@dsboulder thanks! So glad to see this nomination come in.

@rkoster, we'll take the 👍 reaction above as an acceptance of the nomination.

**Comment by emalm** [comment]
Closing as the 2022 TOC election has concluded.
