### ISSUE TITLE
Standardize WG metadata to ease community interactions

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/community#36]
## Expected behavior

As a community member
* in order to easily discover and interact with CFF working groups
* I need a consistent/standardized way to consume WG metadata:
   * WG members and their roles (such as [istio/istio/CODEOWNERS](https://github.com/istio/istio/blob/master/CODEOWNERS) or [kubernetes-sigs/service-catalog/OWNERS](https://github.com/kubernetes-sigs/service-catalog/blob/master/OWNERS))
   * Roadmap pointer
   * Public CI pointer (and associated git repo)
   * Pointers to design and architecture documents
   * List of git repos
   * Slack channel
   * Security contacts (in addition to CFF level security contacts)

## Observed behavior

https://github.com/cloudfoundry/community/blob/9fc193fb0a0423a6f9dac49f25a903ea4240687d/GOVERNANCE.md#L17-L40 does not yet describe standard format for WG to expose their metadata/assets to the community

Here is a list sources of information regarding CFF projects available to the community
* the list of project (prior to #6) at https://www.cloudfoundry.org/projects/ is largely outdated.
* the https://github.com/cloudfoundry/pmc-notes/ repo provides up-to-date project news to the community
* @gberche-orange maintains at https://github.com/cloudfoundry-community/cf-docs-contrib/wiki/Design-Documents pointers to 
   * project roadmaps (in pivotal tracker or github projects)
   * project public CI and their associated git repos
   * architecture and design documents

**Comment by chipchilders** [comment]
Absolutely agree with this. Does anyone want to propose a PR that addresses more details about metadata for the WG's? @cloudfoundry/governance-wg or anyone else?

**Comment by gberche-orange** [comment]
thanks @chipchilders 

BTW, it seems that @cloudfoundry/governance-wg is'nt yet public as https://github.com/orgs/cloudfoundry/teams/governance-wg is returning a 404. Any chance to open read visibility of teams in the cloudfoundry community for everyone ?

**Comment by gberche-orange** [comment]
Unfortunately, according https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-organizations-and-teams/changing-team-visibility github organization teams seems to only be visible to organization members
Any chance for CFF to add representative of CFF members to the organization, or more generally CFF community users ?

**Comment by chipchilders** [comment]
> Unfortunately, according https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-organizations-and-teams/changing-team-visibility github organization teams seems to only be visible to organization members.
> 
> Any chance for CFF to add representative of CFF members to the organization, or more generally CFF community users ?

Opened #38 to address this question.

**Comment by chipchilders** [comment]
> thanks @chipchilders
> 
> BTW, it seems that @cloudfoundry/governance-wg is'nt yet public as https://github.com/orgs/cloudfoundry/teams/governance-wg is returning a 404. Any chance to open read visibility of teams in the cloudfoundry community for everyone ?

Sorry... that team was specifically to get through the process of forming a proposal here in this repo. The members today are: @jenspinney @loewenstein @julz @friegger @smoser-ibm @aclark801 (and myself for support).

**Comment by chipchilders** [comment]
TOC will need to address this once started. Tagging with icebox.
