### ISSUE TITLE
user experience as 1st class asset with its associated governance

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/community#37]
Cloud Foundry's user experience is recognized as a key differentiator w.r.t. alternative products & communities.

To maintain and further improve this asset, I believe that UX needs to be valued by the community process as an asset which deserves as much care/inclusivity/process as other assets such as technical (code, design) or marketing (branding, logs) or legals (IP).

In the past, I believe CloudFoundry has brought innovative and solid UX as a result of the following practices by key contributors (in particular Pivotal):
* strong product management with investments in user research and metrics to make right product and UX decisions
* gathering community feedback on user experience alternatives (through design proposals, surveys)
* ensuring a strong backward compatibility for UX: systematically gathering community feedback on considered breaking changes in APIs, UX (including CF CLI flag or output changes)
* ensuring an overall consistent UX across CF projects, with efforts such as [ubiquitous language](https://martinfowler.com/bliki/UbiquitousLanguage.html) across projects, documentation, and marketing activities. 

Some suggestions for "rebooted" governance:
* While WGs have full autonomy for managing technical decisions in their scope along with TOC oversight, the 
work affecting CF UX should have a global channel to ask for community feedback (was previously cf-dev@)
* CF UX artefacts (user research, results of community surveys, user experience and design work - such as UX prototypes/personas -,  and scenarios, user documentation) should be subject to clear governance, ideally be open to read/contribute by the community while protecting sales/customer details by contributors.
* There should be a process to handling UX-related community disagreements (such as deprecation windows for V2 to V3 API, or CF-on-VMS to CF-on-K8S )

**Comment by loewenstein** [comment]
@gberche-orange do you think that as a first step having a WG dedicated to UX would help?

**Comment by gberche-orange** [comment]
@loewenstein I don't believe a dedicated WG to UX would help for this kind of crosscutting aspects applying to all WGs. 

To take analogies with other tranversal topics, would you think that the following dedicated WGs make sense ? security WG, documentation WG , licensing/intellectual property WG, automated testing WG, defect management WG, etc...

I'd rather this UX governance be part of GOVERNANCE.md#working-groups, similar to #36, and deserves its own community discussion and concensus

https://github.com/cloudfoundry/community/blob/5184516ab566abbd5b64a724f0261b7993ca8715/GOVERNANCE.md#L17-L33

**Comment by loewenstein** [comment]
@gberche-orange FWIW, knative has working groups for [Documentation](https://github.com/knative/community/blob/master/working-groups/WORKING-GROUPS.md#documentation) and [Productivity](https://github.com/knative/community/blob/master/working-groups/WORKING-GROUPS.md#productivity) and [Istio](https://github.com/istio/community/blob/master/WORKING-GROUPS.md) has one for user experience.

Now, that is of course not saying anything about this being effective and delivering what you would like to see. However, we would get a working group that takes responsibility for community feedback, UX artefacts and that would be involved in (or even in a driver seat for) UX related discussion and disagreements.

Working Group proposals, including CF CLI version deprecations would have to pass UX WG review.

If the TOC would sponsor a UX WG and give them the charter to
- coordinate and execute user research
- gather community feedback
- ensure backwards compatible UX
- ensure consistent UX across projects

Wouldn't that be in line with what you would like to see?

**Comment by gberche-orange** [comment]
> Wouldn't that be in line with what you would like to see?

Yes, if adopted by the community and other WGs, this would satisfy the need for inclusivity I'm expressing.

However, my personal intuition is that centralizing all UX related activities in a dedicated UX WG would create bottlenecks and may end up in a situation with a UX WG being disconnected from WGs actually implementing the features. Would be good to have feedback from current CFF projects to enrich perspectives.
