### ISSUE TITLE
Consider setting specific standards for adding new members to the CFF GH orgs

### ISSUE THREAD

**Issue by chipchilders** [cloudfoundry/community#38]
Comment that triggered this issue:

> Unfortunately, according https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-organizations-and-teams/changing-team-visibility github organization teams seems to only be visible to organization members.
> 
> Any chance for CFF to add representative of CFF members to the organization, or more generally CFF community users ?
> 
_Originally posted by @gberche-orange in https://github.com/cloudfoundry/community/issues/36#issuecomment-730239692_

As of now, we do not have clear info about what is required to get org membership. It would be good to describe that here: https://github.com/cloudfoundry/community/blob/main/ROLES.md

**Comment by chipchilders** [comment]
labeling as icebox for TOC to own

**Comment by emalm** [comment]
Addressed in [RFC 0002](https://github.com/cloudfoundry/community/blob/main/toc/rfc/rfc-0002-github-members.md).
