### ISSUE TITLE
Can governance documents and COC also be brought to github?

### ISSUE THREAD

**Issue by bkrannich** [cloudfoundry/community#40]
I believe the topic was discussed before but seeing the link from the README.md reminded me that it would be great to keep the documents under https://www.cloudfoundry.org/governance/ in Github as well, especially to have a clear version history (for me, it's less about the format PDF vs. markdown but more on traceability).

**Comment by bkrannich** [comment]
Same goes for Code of Conduct

**Comment by chipchilders** [comment]
Yes. I will handle that, and ensure that the code ownership is indicated correctly.
