### ISSUE TITLE
Determine a plan for when it's a good point in time for legal teams to review

### ISSUE THREAD

**Issue by bkrannich** [cloudfoundry/community#42]
My understanding is that the updates of the Governance docs requires a formal approval voting at some point in time. In order to do this, companies usually ask their legal teams for review of the new terms.

From experience, this requires a bit of time (what's usually requested is two weeks) plus ideally an advance notice/projection on when this is going to happen, roughly.

**Comment by chipchilders** [comment]
I will own this process and ensure that the GB will have at least 2 weeks for voting on the part they have responsibility to approve.

**Comment by chipchilders** [comment]
reviewed and approved by GB
