### ISSUE TITLE
Update LFX project control center to match the community repo

### ISSUE THREAD

**Issue by rkoster** [cloudfoundry/community#483]
There seem to be a lot of tools provided by LFX that we as a community are currently not using to their full potential. I'm mainly talking about the Security and Insights dashboards. To properly use these tools it seems like we need to use LFX Project Control Center to associate repositories with projects (maybe per working group or area): https://docs.linuxfoundation.org/lfx/project-control-center/tools/security/onboarding-projects-from-github#associating-individual-repositories-to-the-project

Another aspect that needs to be taken into account is providing access to the appropriate people. It seems like this is managed via the creation of committees: https://community.lfx.dev/t/set-up-project-committees-to-improve-coordination-reporting-and-meeting-management/128

As a first step we probably first want a TOC committee and maybe groups per working group area so that approvers can triage security scanning reports.

**Comment by rkoster** [comment]
cc @cloudfoundry/toc

**Comment by christopherclark** [comment]
@rkoster I've followed up with the LF about getting Cloud Foundry's subprojects to correlate with working groups, which will enable Insights and LFX Security dashboard by working group.  I'm hoping to have this done before EOY, and will keep you posted here.

**Comment by beyhan** [comment]
Hi @christopherclark,

do we have the LFX Insights and Security dashboards in place or the plans here changed? I saw that there a new version of the LFX dashboards available yet. If not applicable any more we can close this.

**Comment by beyhan** [comment]
Still relevant and Chris will provide updates.

**Comment by christopherclark** [comment]
Update: I have been told this feature is ready and should roll out in December

**Comment by beyhan** [comment]
The LFX projects boards could be find in https://insights.lfx.linuxfoundation.org/foundation/cloud-foundry/projects. Closing this for now.
