### ISSUE TITLE
TOC Bootstrapping

### ISSUE THREAD

**Issue by chipchilders** [cloudfoundry/community#52]
Proposal:

First election places 5 people in seats. First two highest number of votes start 2 year terms. 3 next are 1 year terms. Election cycle kicks off a year later.

Initial elig proposal:

Need to propose who is elig to run for TOC initially, since the requirements post formation include roles that don't exist during startup. What if TOC elig == vote elig?

**Comment by jenspinney** [comment]
I also want to note that we discussed (but didn't come to a conclusion on) the more general question of whether TOC eligibility should equal voter eligibility (that is, you don't need to be a WG lead or approver to be a member of the TOC) in all elections, not just the initial election. The reasoning being that if we trust the election process enough to allow any contributor to be a candidate for the TOC in the first election, why wouldn't that also work in subsequent elections?
