### ISSUE TITLE
Cleanup the access permissions of github users not managed by the CFF ogranization automation 

### ISSUE THREAD

**Issue by beyhan** [cloudfoundry/community#528]
The current version of the automation which we have in place maintains the access permissions for the CFF organization repositories on github teams level. It doesn't manage the access permissions of individual github users to github repositories. That is why there are still users with access permissions to the CFF organization repositories which shouldn't be there.  This issue is about finding a way for automatic and periodical cleanup of such user permissions. 

This is a result of the discussions during the [TOC meeting on 2023-02-07](https://docs.google.com/document/d/1ng8rAcnrCbTm5RVNAKZ_ptqXiwcBIPgC8rbYp6A8lUo/edit#heading=h.3xng24xf236).

**Comment by Gerg** [comment]
For the [App Runtime Interfaces working group](https://github.com/cloudfoundry/community/blob/main/toc/working-groups/app-runtime-interfaces.md), the following users are expected to lose access to the respective repositories:

@KevinJCross -  cloudfoundry/app-autoscaler-cli-plugin
@stanimirovn -  cloudfoundry/docs-buildpacks
@hibell -  cloudfoundry/ibm-websphere-liberty-buildpack
@kevin-ortega -  cloudfoundry/ibm-websphere-liberty-buildpack
@sclevine -  cloudfoundry/dotnet-core-buildpack
@arjun024 -  cloudfoundry/buildpacks-ci
@brayanhenao -  cloudfoundry/buildpacks-ci
@GarimaSharma -  cloudfoundry/buildpacks-workstation
@mgibson1121 -  cloudfoundry/buildpacks-workstation
@arjun024 -  cloudfoundry/libbuildpack
@brayanhenao -  cloudfoundry/libbuildpack
@arjun024 -  cloudfoundry/switchblade
@brayanhenao -  cloudfoundry/switchblade
@matt-royal -  cloudfoundry/cloud_controller_ng
@soochow -  cloudfoundry/capi-team-checklists
@weymanf -  cloudfoundry/cc-uploader
@maximilien -  cloudfoundry/cli-i18n
@davidschachner -  cloudfoundry/cli-docs-scripts
@blgm -  cloudfoundry/jsonry
@xtreme-bozhidar-lenchov -  cloudfoundry/notifications-release

If you would like to maintain access, please submit a PR as described in [Roles.md](https://github.com/cloudfoundry/community/blob/main/toc/ROLES.md#promotion-and-revocation) to add yourself to the appropriate working group area(s). I'm happy to help with this process however I can.

Thanks!

**Comment by rkoster** [comment]
For Foundational Infrastructure:
- @Cryogenics-CI -  cloudfoundry/docs-bbr (cc @dlresende)
- @BarrAndrea -  cloudfoundry/docs-credhub
- @stanimirovn -  cloudfoundry/docs-uaa
- @cf-osl-bot -  cloudfoundry/credhub
- @aclement -  cloudfoundry/credhub-acceptance-tests
- @xandroc -  cloudfoundry/credhub-acceptance-tests
- @davidschachner -  cloudfoundry/credhub-acceptance-tests
- @aclement -  cloudfoundry/credhub-cli
- @Samze -  cloudfoundry/credhub-cli
- @avade -  cloudfoundry/credhub-cli
- @xchapter7x -  cloudfoundry/credhub-cli
- @jhvhs -  cloudfoundry/credhub-cli
- @spikymonkey -  cloudfoundry/credhub-cli
- @alex-slynko -  cloudfoundry/credhub-cli
- @shinji62 -  cloudfoundry/credhub-cli
- @davidschachner -  cloudfoundry/credhub-cli
- @ablease -  cloudfoundry/credhub-cli
- @pcf-sec-eng-bot -  cloudfoundry/credhub-cli
- @cf-osl-bot -  cloudfoundry/credhub-cli
- @credhub-ci-bot -  cloudfoundry/credhub-cli
- @brightzheng100 -  cloudfoundry/secure-credentials-broker
- @pivotal-radojko-drcelic -  cloudfoundry/secure-credentials-broker
- @abg -  cloudfoundry/backup-and-restore-sdk-release
- @colins -  cloudfoundry/backup-and-restore-sdk-release
- @pcf-sec-eng-bot -  cloudfoundry/bosh-backup-and-restore
- @jhunt -  cloudfoundry/bosh-backup-and-restore-test-releases
- @geofffranks -  cloudfoundry/bosh-backup-and-restore-test-releases
- @zrob -  cloudfoundry/homebrew-tap
- @voelzmo -  cloudfoundry/homebrew-tap
- @pcf-sec-eng-bot -  cloudfoundry/homebrew-tap
- @cf-infra-bot -  cloudfoundry/homebrew-tap
- @6palace -  cloudfoundry/cf-identity-acceptance-tests-release
- @matt-royal -  cloudfoundry/cf-uaac
- @APShirley -  cloudfoundry/omniauth-uaa-oauth2
- @pabloarodas -  cloudfoundry/uaa
- @ram-pivot -  cloudfoundry/uaa
- @pabloarodas -  cloudfoundry/uaa-release
- @ram-pivot -  cloudfoundry/uaa-release
- @pcf-core-services-writer -  cloudfoundry/mysql-backup-release
- @pcf-core-services-writer -  cloudfoundry/mysql-monitoring-release
- @pcf-core-services-writer -  cloudfoundry/pxc-release
- @pivotal-mysql-ci-writer -  cloudfoundry/pxc-release
- @concourse-metrix -  cloudfoundry/bosh-system-metrics-server-release
- @oratos-bot -  cloudfoundry/syslog-release
- @StefanWutz -  cloudfoundry/concourse-infra-for-gke
- @AbelHu -  cloudfoundry/bosh-azure-cpi-release
- @NingKuang -  cloudfoundry/bosh-azure-cpi-release
- @SanikaGawhane -  cloudfoundry/bosh-vsphere-cpi-release
- @andyliuliming -  cloudfoundry/bosh-azure-cpi-release
- @bingosummer -  cloudfoundry/bosh-azure-cpi-release
- @bosh-ci-push-pull -  cloudfoundry/bosh
- @bosh-ci-push-pull -  cloudfoundry/bosh-agent
- @bosh-ci-push-pull -  cloudfoundry/bosh-bbl-ci-envs
- @bosh-ci-push-pull -  cloudfoundry/bosh-compiled-releases-index
- @bosh-ci-push-pull -  cloudfoundry/bosh-deployment
- @bosh-ci-push-pull -  cloudfoundry/bosh-utils
- @bosh-ci-push-pull -  cloudfoundry/os-conf-release
- @bosh-windows-ci -  cloudfoundry/stembuild
- @briannebrown -  cloudfoundry/bosh-alicloud-light-stemcell-builder
- @briannebrown -  cloudfoundry/stemcells-alicloud-index
- @cf-infra-bot -  cloudfoundry/bosh-bootloader
- @cppforlife -  cloudfoundry/bosh-cpi-go
- @cppforlife -  cloudfoundry/bosh-docker-cpi-release
- @cppforlife -  cloudfoundry/bosh-virtualbox-cpi-release
- @cppforlife -  cloudfoundry/bosh-warden-cpi-release
- @craigdbarber -  cloudfoundry/bosh-google-cpi-release
- @davewalter -  cloudfoundry/bosh-bootloader
- @davewalter -  cloudfoundry/jumpbox-deployment
- @donacarr -  cloudfoundry/bosh-softlayer-cpi-release
- @drich10 -  cloudfoundry/bosh-deployment-resource
- @dsboulder -  cloudfoundry/bosh-azure-cpi-release
- @edwardstudy -  cloudfoundry/bosh-softlayer-cpi-release
- @evandbrown -  cloudfoundry/bosh-google-cpi-release
- @gossion -  cloudfoundry/bosh-azure-cpi-release
- @gu-bin -  cloudfoundry/bosh-softlayer-cpi-release
- @jfmyers9 -  cloudfoundry/bosh-virtualbox-cpi-release
- @johnsonj -  cloudfoundry/bosh-gcscli
- @ktchen14 -  cloudfoundry/bosh-vsphere-cpi-release
- @mattcui -  cloudfoundry/bosh-softlayer-cpi-release
- @maximilien -  cloudfoundry/bosh-softlayer-cpi-release
- @nehagjain15 -  cloudfoundry/bosh-vsphere-cpi-release
- @nhsieh -  cloudfoundry/bosh-bootloader
- @openstack-cpi -  cloudfoundry/bosh-openstack-cpi-release
- @pcfazuretools -  cloudfoundry/bosh-azure-cpi-release
- @pvaramballypivot -  cloudfoundry/docs-bosh
- @ritazh -  cloudfoundry/bosh-azure-cpi-release
- @rnandi -  cloudfoundry/bosh-cpi-ruby
- @sethboyles -  cloudfoundry/bosh-vsphere-cpi-release
- @thomas1206 -  cloudfoundry/bosh-azure-cpi-release
- @voelzmo -  cloudfoundry/bosh-openstack-cpi-release
- @xiaozhu36 -  cloudfoundry/bosh-alicloud-light-stemcell-builder
- @xiaozhu36 -  cloudfoundry/stemcells-alicloud-index
- @yeshwantbabar -  cloudfoundry/bosh-vsphere-cpi-release
- @zhanggbj -  cloudfoundry/bosh-softlayer-cpi-release

👉 If it is a bot --> it will need to be added to the [bot group](https://github.com/cloudfoundry/community/blob/eb170544bf1556a8d18631c7ad49b59146fce536/toc/working-groups/app-runtime-platform.md?plain=1#L44-L51).
👉 If it is for an individual --> you can [create a PR to become an approver in your area](https://github.com/cloudfoundry/community/blob/main/toc/ROLES.md#approver).
👉 If the permissions are no longer needed --> do nothing! they will be deleted in Jan 2024.
👉 Need help? ---> ask!
