### ISSUE TITLE
Decide whether TOC meeting notes should be viewable by all

### ISSUE THREAD

**Issue by jenspinney** [cloudfoundry/community#53]
I noticed that I don't have access to read the meeting notes linked to from the [Istio](https://github.com/istio/community/blob/d32f6fcd0b11a2463a28fca7f2d5e67bf1b24106/TECH-OVERSIGHT-COMMITTEE.md#committee-mechanics) or the [Knative](https://github.com/knative/community/blob/4a14937a5e4b634ca24f1923a92eef1d2c1a9ece/TECH-OVERSIGHT-COMMITTEE.md#committee-meeting) TOC descriptions. It made me wonder why those notes are not publicly viewable. In the interest of transparency, they seem like an artifact we'd want the whole community to be able to read.

My initial opinion is that we should clarify that the meeting notes from the TOC should be viewable by all. It's possible there's some nuance I'm missing here that led Knative and Istio to decide to make their TOC notes private, and I'm curious to hear whether folks have reasons to support that decision.

**Comment by loewenstein** [comment]
@jenspinney The Istio and I guess the Knative TOC meeting notes are viewable by anyone who joins the Istio and Knative Google Group (with the click of a button). That's the same for all technical design documents.

**Comment by emalm** [comment]
Oh, yeah, I'm in the Knative Google group myself and so didn't even notice there was a barrier.

+1 to making the CF TOC notes journal public, and to making sure that is stated explicitly in the committee mechanics section. Currently it says the meeting notes will be "published" but is not specific about the openness of access to that document.
