### ISSUE TITLE
Remove org members for which the invite has failed

### ISSUE THREAD

**Issue by rkoster** [cloudfoundry/community#535]
Just noticed there are a bunch of people for which the invite keeps failing: https://github.com/orgs/cloudfoundry/people/failed_invitations

We should probably find a way to remove these people from the contributor's list automatically.

**Comment by rkoster** [comment]
These people will need to be removed from: https://github.com/cloudfoundry/community/blob/main/org/contributors.yml

**Comment by AP-Hunt** [comment]
https://github.com/cloudfoundry/community/pull/543
