### ISSUE TITLE
Paketo Buildpacks Steering Committee Candidate Nomination for Forest Eckhardt

### ISSUE THREAD

**Issue by ForestEckhardt** [cloudfoundry/community#605]
Candidate Name: Forest Eckhardt

Candidate GitHub Username: @ForestEckhardt

Affiliation: VMware

Nomination Statement: I have been working on the Paketo Buildpacks project since its inception. I am maintainer of several language subteams I am heavily invested in the Paketo community as a whole! I would love to be able to have a leading role in shaping this project going forward.

**Comment by beyhan** [comment]
Closing as the 2023 Paketo Buildpacks Steering Committee election has concluded.
