### ISSUE TITLE
Paketo Buildpacks Steering Committee Candidate Nomination for Daniel Mikusa

### ISSUE THREAD

**Issue by dmikusa** [cloudfoundry/community#608]
Candidate Name: Daniel Mikusa

Candidate GitHub Username: @dmikusa 

Affiliation: N/A - Independent 

Nomination Statement: As a current member of the Paketo Steering Committee, it has been a privilege to help the project grow and mature. I am seeking a nomination so that I can continue this effort. I believe we can continue to grow the project by listening to our users, by fostering an open and welcoming community, and by mentoring those that want to contribute to the project. If re-elected, those will be my areas of focus.

**Comment by beyhan** [comment]
Closing as the 2023 Paketo Buildpacks Steering Committee election has concluded.
