### ISSUE TITLE
Paketo Buildpacks Steering Committee Candidate Nomination for Jan von Löwenstein

### ISSUE THREAD

**Issue by loewenstein** [cloudfoundry/community#609]
Candidate Name: Jan von Löwenstein

Candidate GitHub Username: @loewenstein

Affiliation: SAP SE

Nomination Statement: 
I have been active in the Cloud Foundry community (as Bosh maintainer and later founding TOC member) since 2015. My team has been looking into Paketo buildpacks since around 2019 and we ramped up our involvement quite a bit since 2022 / 2023 with currently three contributors.
Managing the backlog of my team, I speak a lot with buildpack users. At the same time I believe I still hold enough technical grasp to be able to translate between requirements and technical project direction.

**Comment by beyhan** [comment]
Closing as the 2023 Paketo Buildpacks Steering Committee election has concluded.
