### ISSUE TITLE
TOC Candidate Nomination for Jesse Alford

### ISSUE THREAD

**Issue by anEXPer** [cloudfoundry/community#612]
Candidate Name: Jesse Alford

Candidate GitHub Username: @anEXPer

Affiliation: none

Nomination Statement: This being a self nomination, I'll speak in the first-person. I've worked on CF for almost ten years. I was anchor of the release integration team that conceived of and developed cf-deployment, guided the design of the v6 CLI, orchestrated the transition of Pivotal Web Services from cf-release to multi-deployment/cell-block cf-deployment, and have recently resigned from VMware after years of being a Technology Lead focused on release, packaging, and upgrade related issues for TAS, VMware's commercialized distribution.

I care deeply about Cloud Foundry and related technologies like Concourse, and bring significant experience and expertise in transitions and roadmaps through eras of technological and organizational change.

**Comment by christopherclark** [comment]
@rkoster @stephanme @emalm @AP-Hunt @beyhan 

Per the section [7(e)(i) in the CFF Charter](https://github.com/cloudfoundry/community/blob/main/governing-board/charter.md), we'll need a majority of the TOC to approve an exemption for Jesse to run for a TOC seat. If you could, please comment your approval (or disapproval) on this issue.

**Comment by rkoster** [comment]
TOC, please indicate your approval or objection via 👍 / 👎 reaction on this comment or reply on the discussion

**Comment by beyhan** [comment]
Closing as the 2023 TOC election has concluded.
