### ISSUE TITLE
TOC Candidate Nomination for Chris McGowan

### ISSUE THREAD

**Issue by pburkholder** [cloudfoundry/community#613]
Candidate Name: Chris McGowan

Candidate GitHub Username: @ChrisMcGowan

Affiliation: cloud.gov

Nomination Statement:

Chris is a senior engineer with cloud.gov, the U.S. government's primary public sector Cloud Foundry service. He's a seasoned Cloud Foundry engineer who has supported operations at GE Predix, Home Depot and for clients of Stark & Wayne. His open-source contributions include numerous repos at [cloud.gov](https://github.com/cloud-gov), various kits, including BOSH and CF App Autoscaler, [for Genesis Community](https://github.com/genesis-community), and [Shield](https://github.com/shieldproject/shield), an open-source backup utility.

I'm nominating Chris because the CFF and the TOC have benefited from public sector representation, as shown by the UK's Lee Porte and Andy Hunt.  Chris is well-suited to carry on that tradition with his deep engineering knowledge coupled with an understanding of compliance and sustainability. He considers deeply the tradeoffs of engineering and architectural decisions, explains technical concepts well, and is a generous colleague. 

In all, he's ideally suited to help Cloud Foundry to continue to grow and thrive.

**Comment by ChrisMcGowan** [comment]
I accept the nomination.

**Comment by rkoster** [comment]
TOC, please indicate your approval or objection via 👍 / 👎 reaction on this comment or reply on the discussion

**Comment by beyhan** [comment]
Closing as the 2023 TOC election has concluded.
