### ISSUE TITLE
TOC Candidate Nomination for Amelia Downs

### ISSUE THREAD

**Issue by emalm** [cloudfoundry/community#614]
Candidate Name: Amelia Downs

Candidate GitHub Username: @ameowlia

Affiliation: VMware

Nomination Statement:

Amelia has been a stellar contributor and leader within the Cloud Foundry community since she joined it in 2016. Most recently, she has been serving as the Technical and Execution Lead for the Application Runtime Platform Working Group since its inception and has been instrumental in shaping the collaboration practices and healthy activity within that working group. 

She has also provided deep technical leadership and expertise within primarily the Networking and the Diego areas of the Cloud Foundry Application Runtime, driving forward substantial improvements to gorouter, container-to-container networking, TCP router, Envoy-based route integrity, NATS security, and dynamic application security groups, among other areas. She has deep empathy for the application developers, platform engineers, and security teams that Cloud Foundry serves and consistently keeps their needs and experiences in mind when developing effective solutions for them.

Additionally, Amelia has been an engaging and effective communicator for the Cloud Foundry project, delivering excellent technical presentations at Cloud Foundry Summits and other events and serving as a model for clear and actionable messaging across the community. She also has experience contributing to other open-source projects, having spent several months participating in and contributing to the Golang project, and consequently has a thorough understanding of how open-source projects can be effective in cultivating healthy community participation.

Overall, Amelia would be an excellent member of the CFF TOC, and I cannot think of a better representative of our community than her.

**Comment by ameowlia** [comment]
I accept the nomination.

**Comment by beyhan** [comment]
Closing as the 2023 TOC election has concluded.
