### ISSUE TITLE
Org automation fails due to missing default branch for some bosh repos

### ISSUE THREAD

**Issue by stephanme** [cloudfoundry/community#645]
https://github.com/cloudfoundry/community/actions/runs/5526042493/jobs/10080303915 failed with e.g.

```
{"component":"peribolos","error":"status code 422 not one of [200], body: {\"message\":\"Validation Failed\",\"errors\":[{\"message\":\"The branch main was not found. Please push that ref first or create it via the Git Data API.\",\"resource\":\"Repository\",\"field\":\"default_branch\",\"code\":\"invalid\"}],\"documentation_url\":\"https://docs.github.com/rest/repos/repos#update-a-repository\"}","file":"k8s.io/test-infra/prow/cmd/peribolos/main.go:1052","func":"main.configureRepos","level":"error","msg":"failed to update repository","repo":"bosh-io-stemcells-windows-index","severity":"error","time":"2023-07-12T00:32:20Z"}
```

for the following repos:
- bosh-io-stemcells-windows-index
- bosh-package-nginx-release
- bosh-io-stemcells-softlayer-index
- bosh-package-golang-release
- bosh-io-web
- bosh-io-stemcells-core-index
- bosh-package-ruby-release
- bosh-io-releases-index
- bosh-package-java-release
- bosh-io-stemcells-cpi-index
- bosh-package-python-release
- bosh-io-releases
- bosh-io-worker

These repos were moved from org bosh-io to cloudfoundry by #512 .

Looks like these repos use `master` as default branch but #512 configured `main` as default branch which doesn't exist.

**Comment by jpalermo** [comment]
They should all have been renamed from `master` to `main` now
