### ISSUE TITLE
Create a new repository `cloudfoundry/otel-collector-release` for ARP WG

### ISSUE THREAD

**Issue by ctlong** [cloudfoundry/community#709]
👋 Hi there!

The ARP WG has been working on adding an OTel Collector integration to CF-D, as outlined in [RFC: Add OTel Collector for aggregate metric egress](https://github.com/cloudfoundry/community/blob/main/toc/rfc/rfc-0018-aggregate-metric-egress-with-opentelemetry-collector.md).

Our OTel Collector distribution is currently co-located in the [loggregator-agent release](https://github.com/cloudfoundry/loggregator-agent-release) which is starting to get confusing from a release versioning perspective.

If our WG lead, @ameowlia, and the TOC, are onboard we'd like to ask y'all to create a new repository for this work and assign it to the ARP WG Logging & Metrics area. We suggest `cloudfoundry/otel-collector-release` as the name.

Thanks! Let me know if I you have any questions, or if I can help with the work in any way 😄

**Comment by stephanme** [comment]
Hi Carson,

You can simply create a PR on this repo that:
- adds the new repo to https://github.com/cloudfoundry/community/blob/main/org/cloudfoundry.yml
- adds the repo name to the correct WG area in the yaml section of https://github.com/cloudfoundry/community/blob/main/toc/working-groups/app-runtime-platform.md

Then the PR goes to the process sketched out in [rfc-0007-repository-ownership.md](https://github.com/cloudfoundry/community/blob/main/toc/rfc/rfc-0007-repository-ownership.md), i.e. it needs WG lead and TOC approval. Once merged, the repo is created automatically and assigned to the correct WG area github teams.

Best regards,
Stephan
