### ISSUE TITLE
We should define how nomination for the TOC works

### ISSUE THREAD

**Issue by loewenstein** [cloudfoundry/community#72]
https://github.com/cloudfoundry/community/blob/main/TOC.md#candidate-eligibility omits any details of how, where and when (until when) self-nomination can occur.

**Comment by chipchilders** [comment]
create a stub election folder with README, voters and ballot.md files

define election cycle in e-X form
  Announce election cycle and specify automatically included voters (e-4 weeks)
  Accept TOC nominations and voter eligibility additions (e-4 through e-2)
  nominations close / prep ballot system (1 to 2 days)
  Voting e-2 through e-0
  2 days later announce
  TOC takes on roles immediately

Annual cycle happens based on when the first election will actually happen (avoid august and december)

nominations flow through PRs

**Comment by chipchilders** [comment]
Should not have been closed. Push only partially resolved.

**Comment by chipchilders** [comment]
FWIW, we are going with an issue template for this first election and can refine based on feedback / experience.

**Comment by AP-Hunt** [comment]
This was done, for [example in 2022](https://github.com/cloudfoundry/community/tree/main/elections/2022/TOC)
