### ISSUE TITLE
We should provide details on the voter eligibility exceptions

### ISSUE THREAD

**Issue by loewenstein** [cloudfoundry/community#73]
https://github.com/cloudfoundry/community/blob/main/TOC.md#voter-eligibility mentions only vaguely that there should be a form.

I would suggest that we use an issue template on this repository for this. Thoughts?

**Comment by chipchilders** [comment]
Makes total sense to me!

**Comment by chipchilders** [comment]
Sorry about that... I committed the template directly. Will do a PR now.
