### ISSUE TITLE
Remove the Github users added as "Outside collaboration" to the cloudfoundry org

### ISSUE THREAD

**Issue by beyhan** [cloudfoundry/community#774]
During the [TOC meeting](https://docs.google.com/document/d/1qGrDBWBrO8_FrPXmosKD9fa67NPtT4p5NhHKN8ideY0/edit) on 6th of February we decided to remove the Github users added as [Outside collaborators](https://github.com/orgs/cloudfoundry/outside-collaborators) to the [cloudfoundry](https://github.com/orgs/cloudfoundry) org (meeting recording is available [here](https://www.youtube.com/watch?v=ORsskP8UYHw&list=PLhuMOCWn4P9jHiD9yAiB8EB-mU5HPgixn&index=1)). This is because we have now automation in place to manage the members, teams and repositories of the cloudfoundry org and there shouldn't be a need to be on that list. On our [Roles](https://github.com/cloudfoundry/community/blob/main/toc/ROLES.md) page you can find the different roles we have in the community. E.g. if you still need to be member of the cloudfoundry org which means to be listed as contributor please create a pr like [this](https://github.com/cloudfoundry/community/pull/672) and the TOC will take care of it. If you contribute to a working group you could apply for a [reviewer](https://github.com/cloudfoundry/community/blob/main/toc/ROLES.md#promotion-to-reviewer-or-approver) or [approver](https://github.com/cloudfoundry/community/blob/main/toc/ROLES.md#promotion-to-reviewer-or-approver) role but this require review and approval from the corresponding working group. We plan to execute the remove in two weeks from now. Please provide feedback by commented on this issue if there is something we missed.
FYI:
@aadeshmisra
@ben-schumacher
@cf-for-k8s-release-bot
@cf-osl-bot
@ecs-ci-robot
@focus97
@garethjevans
@ikapelyukhin
@jaimegag
@joyvuu-dave
@MarcSchunk
@oratos-bot
@Paul-TT
@pcf-event-alerts-cibot
@pcf-redis-bot
@phakob
@pivotal-anthony-rios
@pivotal-Josh-Gainey
@pivotal-yugam-sharma
@rarni-pivotal
@ritazh
@RuntimeOG
@sedouard
@sipid-ci
@svrc
@vvaradhan

**Comment by ameowlia** [comment]
Given our typical 2 weeks notice, let's plan to remove these accounts from outside collaborators on Tuesday Feb 20th.
