### ISSUE TITLE
cloudfoundry-community org is not accessible

### ISSUE THREAD

**Issue by vipinvkmenon** [cloudfoundry/community#776]
The [cloudfoundry-community org](https://github.com/cloudfoundry-community/go-cfclient/) is not reachable.
There were several repositories like the go-cfclient and the cf terraform-provider and several others that were extensively used.
Any idea as to why it was removed or what is the plan here? or who to contact for the same?

Thanks

**Comment by biradrags** [comment]
+1 tf provider is not accessible

**Comment by beyhan** [comment]
I'm trying to clarify. 

FYI: the cloudfoundry-community org isn't managed by the TOC

**Comment by beyhan** [comment]
The topic is discussed in https://cloudfoundry.slack.com/archives/C02FL4A2K/p1707462526630869. From the Slack thread:

> nabramovitz
>   [24 minutes ago](https://cloudfoundry.slack.com/archives/C02FL4A2K/p1707462973757839?thread_ts=1707462526.630869&cid=C02FL4A2K)
> The org was hit by a hacker that deleted all the repos.  A request to GitHub to restore  everything has been made.
>

**Comment by biradrags** [comment]
they're back!!! Hooray! 
Thank you

**Comment by vipinvkmenon** [comment]
This is great. But we have to think on how we can prevent this and keep an eye on some of the most important repos in that ORG...(Or move them here if that's a possibility)

**Comment by vipinvkmenon** [comment]
Considering that the repo is restored for now I'm closing this issue.
