### ISSUE TITLE
Moving repos from bosh-prometheus account to cloudfoundry account

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/community#787]
This is a follow up of https://github.com/cloudfoundry/community/issues/778#issuecomment-1966883729 where the maintainers of the https://github.com/bosh-prometheus/ org would like to move their repos onto the cloudfoundry org, as discussed into https://github.com/bosh-prometheus/prometheus-boshrelease/issues/491.

This issue (which uses one of the public issue templates https://github.com/cloudfoundry/community/tree/main/.github/ISSUE_TEMPLATE has should be removed the `election` label) is to start this discussion with the TOC

/CC @ArthurHlt @benjaminguttmann-avtq @bkez322 @frodenas @gmllt @mdimiceli @mkuratczyk

**Comment by beyhan** [comment]
We discussed this during the TOC meeting yesterday (5th of March) shortly. This week TOC members will look into this async and continue the discussion during the next TOC meeting. 

FYI @christopherclark

**Comment by beyhan** [comment]
Hi @gberche-orange,
I would like to bring some questions up which will help us during the next TOC meeting by discussing this issue. It will be great if you could add some details on the following questions:

1. To which CFF working group do you think they should move? You can find a list of the CFF working groups [here](https://github.com/cloudfoundry/community/tree/main/toc/working-groups). 
1.1 What is the primary use case of the repos in the `bosh-prometheus` org (CF, CF apps or BOSH monitoring)? 
2. How do you imagine the future maintenance? 
2.1.  Will the current maintainers of the repositories continue to maintain them?
2.2  Do you plan any changes for the existing automation for those repositories?

**Comment by gberche-orange** [comment]
Hi @beyhan,
Thanks for your response, and sorry for late follow up.

> 1. To which CFF working grup do you think they should move? You can find a list of the CFF working groups [here](https://github.com/cloudfoundry/community/tree/main/toc/working-groups).


I'd think that the [foundational-infrastructure](https://github.com/cloudfoundry/community/blob/main/toc/working-groups/foundational-infrastructure.md) seems closest 
> Goals: 
> Operators have a multi-cloud deployment system that can deploy Cloud Foundry onto VMs with a strong set of day 2 operator features.
> Maintain a set of databases, required for the self-contained deployment and operation of BOSH and Cloud Foundry.


> 1.1 What is the primary use case of the repos in the bosh-prometheus org (CF, CF apps or BOSH monitoring)?

The primary use case is "day-two observability" of:
* Bosh control plane (bosh-exporter, bosh-tsdb exporter, graphite_exporter)
* CF (cf-exporter, firehose-exporter, haproxy_exporter, ingestor_exporter)
* CF services (mysql, memcached, redis, stackdriver, consul, elastisearch, influxdb_exporter, rabbitmq
* CF apps (cf-exporter)
* Backup/restore (shield-exporter)

The observability foundation brings:
* prometheus
* grafana
* alertmanager
* pushgateway

> 2. How do you imagine the future maintenance?
> 2.1. Will the current maintainers of the repositories continue to maintain them?

 @benjaminguttmann-avtq and @frodenas gave their support for this change.  @benjaminguttmann-avtq  expressed interest in continuing his maintenance activity. The orange contributors  @gmllt @mdimiceli agreed to proceed with their contributions once the repo would be been onboarded in the cloudfoundry org

> 2.2 Do you plan any changes for the existing automation for those repositories?

I'll leave it up to @benjaminguttmann-avtq to detail the current ci and his view about changes that would make sense.

My understanding is that it is currently concourse-based, and that it may make sense to load the concourse pipelines into a safer ci instance under the CFF governance, along with secured S3 bucket credentials (currently https://github.com/bosh-prometheus/prometheus-boshrelease/blob/f8dd057b6d51b8af6a40a236a251367511836d94/ci/settings.yml#L7-L11 )

**Comment by jpalermo** [comment]
For the bosh releases from the bosh-prometheus org published into https://bosh.io there are a couple options for handling it. All options have different drawbacks.

If you do nothing, and the github redirects work correctly, the existing releases will stay and continue to be published with new versions that are in the cloudfoundry github org repos. This may cause some confusion for people who find the repo then look for the releases on bosh.io and find it under a different name.

If you update the releases in the [releases list](https://github.com/cloudfoundry/bosh-io-releases/blob/28ee2f0bbbcf8587a04240cc7750367f999bbbb9/index.yml#L322-L323) via a PR, they will all be published under the new name. The releases will no longer be listed on the website under the old name, but existing published releases will still be available via the previous paths. However, no new releases will be published under the old paths, so if somebody has automation consuming from the paths, they may not know about the need to change it.

If you both add the new releases and keep the old releases in the list of releases, it will be built and published as both, however this may cause confusion for people looking for the release.

**Comment by beyhan** [comment]
Hi @gberche-orange,

thank you for the detailed answer. We discussed this during the TOC meeting today (19.03.24). Our conclusion was that it makes sense to move actively maintained repositories, which are directly related to CF or BOSH. Additionally, we think that the repositories should be kept together in their own sub-area and as proposed by you the FI WG seems to be a good fit. We walked over the repositories in the [bosh-prometheus](https://github.com/bosh-prometheus/) organization and our impression is that only the pinned repositories should be in scope. Is the intention of this issue to move all the repositories of the [bosh-prometheus](https://github.com/bosh-prometheus/) organization? E.g. `shield-exporter` doesn't look to be maintained any more and directly related to CF or BOSH.

**Comment by beyhan** [comment]
Hi @gberche-orange,

we discussed this also in the FI WG meeting yesterday and there were no objections. I will suggest you to create a pr like https://github.com/cloudfoundry/community/pull/798 as preparation for the move, so that we can discuss it during the TOC meeting next Tuesday.

**Comment by beyhan** [comment]
@gberche-orange we are closing this. Please proceed as discussed if the interest to move the repos still exist.
