### ISSUE TITLE
Clarify process for TOC Chair

### ISSUE THREAD

**Issue by emalm** [cloudfoundry/community#79]
- How long is the term of the TOC Chair?
- Under what conditions does the TOC select a new chair? Any change to the TOC composition?
- Is chair selection an official Decision of the TOC, to be governed by the TOC decision-making process?
- Can the TOC Chair resign their chair responsibilities while still remaining on the TOC?

**Comment by chipchilders** [comment]
Proposed answers:

- Term - 1 year
- Chair selection - simple majority vote, similar to how similar boards / committees elect chairs: discussion, formally nomination, vote to decide (or confirm if one nomination)
- Chair decision - yes, the TOC decides, and there is nothing in the project charter (where the GB is structured) that includes discussion of the TOC Chair. The only caveat is that the GB can choose to restructure the TOC if it deems it necessary, just like the GB is going to approve the TOC structure itself. A healthy TOC / tech community will not see GB overriding anything, but that "escape hatch" is always there to sort out major problems.
- Chair resign but still be in TOC - Absolutely! I never would have thought of that being linked. Normally, committee chair roles are something that is in addition to being on a committee itself. You can be both chair and on the committee, and you can resign chair while still on committee.
