### ISSUE TITLE
deploy cassandra database as an application using cassandra.jar

### ISSUE THREAD

**Issue by SushmaPradeep** [cloudfoundry/community#816]
Hi Team,
My use case is I have to deploy cassandra database as an application using cassandra.jar. Is it possible to deploy? If yes, please let me know the steps to do.

Thanks,
Sushma.

**Comment by beyhan** [comment]
Hi @SushmaPradeep,

this is not the right place for this question. I would suggest you to ask this question in the [buildpacks](https://cloudfoundry.slack.com/archives/C02HWMDUQ) Slack Channel.
