### ISSUE TITLE
Is it possible to run docker compose on CF ?

### ISSUE THREAD

**Issue by alexkyurtev** [cloudfoundry/community#818]
Hello community , 

I am looking in ways to deploy docker compose on CF environment . Is there any possibility at all ?
Internet and official CF documentation remain silent on the topic . 

Thank you in advance.
Aleksandar Kyurtev

**Comment by beyhan** [comment]
Hello @alexkyurtev,
thank you for your question. Unfortunately, this is not the right place for it. Could you please ask your question in the [#general](https://cloudfoundry.slack.com/archives/C02FL4A2K) Slack channel CFF community.
