### ISSUE TITLE
TOC Candidate Nomination for Ruben Koster

### ISSUE THREAD

**Issue by rkoster** [cloudfoundry/community#879]
Candidate Name: Ruben Koster

Candidate GitHub Username: rkoster

Affiliation: VMware Tanzu (by Broadcom)

Nomination Statement: 
I have been active in the Cloud Foundry community for the past 11+ years supporting the Foundational Infrastructure WG, as TOC member and as CF user who brings new requirements to the CF platform derived from Broadcom use cases. If re-elected I would like to continue contributing to the CF platform evolution and support the CFF community.

**Comment by beyhan** [comment]
Closing because elections are over.
