### ISSUE TITLE
Paketo Buildpacks Steering Committee Candidate Nomination for Jan von Löwenstein

### ISSUE THREAD

**Issue by loewenstein-sap** [cloudfoundry/community#880]
Candidate Name: Jan von Löwenstein

Candidate GitHub Username: @loewenstein-sap (formerly @loewenstein, but I changed my handle)

Affiliation: SAP SE

Nomination Statement: 
I have been active in the Cloud Foundry community (as Bosh maintainer and later founding TOC member) since 2015. I am currently a member of the Paketo Steering Committee. My team has been looking into Paketo buildpacks since around 2019 and we are regular contributors to the project.
Managing the backlog of my team, I speak a lot with buildpack users. At the same time I believe I still hold enough technical grasp to be able to translate between requirements and technical project direction.

**Comment by loewenstein** [comment]
Just a quick confirmation, that I changed my Github handle, but am the same person.

**Comment by beyhan** [comment]
Closing because the elections are over and the results are available in https://github.com/cloudfoundry/community/blob/main/elections/2024/Paketo-SC/results.md
