### ISSUE TITLE
Paketo Buildpacks Steering Committee Candidate Nomination for Jerico Pena

### ISSUE THREAD

**Issue by jericop** [cloudfoundry/community#887]
Candidate Name: Jerico Pena

Candidate GitHub Username: jericop

Affiliation: Rapid7

Nomination Statement: 
I have been an active member of the paketo and cloud native buildpacks community for the last 2 years. Since my involvement I have contributed to pushing forward multi-arch support both within paketo and upstream in the CNB project. I believe I bring a valuable outside perspective not only as an end-user but also as a buildpack author and operator.

**Comment by beyhan** [comment]
Closing because the elections are over and the results are available in https://github.com/cloudfoundry/community/blob/main/elections/2024/Paketo-SC/results.md
