### ISSUE TITLE
[RFC0028] Implement Cloud Native Buildpacks lifecycle

### ISSUE THREAD

**Issue by loewenstein-sap** [cloudfoundry/community#891]
This is a tracking issue for the implementation of https://github.com/cloudfoundry/community/blob/main/toc/rfc/rfc-0028-cnb-lifecycle.md

**Delivered with**:
CF: [cf-deployment v42.3.0](https://github.com/cloudfoundry/cf-deployment/releases/tag/v42.3.0)
CLI: https://github.com/cloudfoundry/cli/pull/3281
Docs: https://docs.cloudfoundry.org/buildpacks/cnb/
 

```[tasklist]
### PRs to be reviewed and merged
- [ ] https://github.com/cloudfoundry/cnbapplifecycle/pull/1
- [ ] https://github.com/cloudfoundry/cnbapplifecycle/pull/2
- [ ] https://github.com/cloudfoundry/diego-release/pull/929
- [ ] https://github.com/cloudfoundry/cloud_controller_ng/pull/3831
- [ ] https://github.com/cloudfoundry/cloud_controller_ng/pull/3778
- [ ] https://github.com/cloudfoundry/cloud_controller_ng/pull/3855
- [ ] https://github.com/cloudfoundry/cli/pull/2871
- [ ] https://github.com/cloudfoundry/cf-deployment/pull/1178
- [ ] https://github.com/cloudfoundry/cf-acceptance-tests/pull/1136
- [ ] https://github.com/cloudfoundry/docs-buildpacks/issues/310
```

**Comment by pbusko** [comment]
>  6\. [ ]                    A follow-up pull request on cloud controller that allows the buildpacks to be in a private registry

https://github.com/cloudfoundry/cloud_controller_ng/pull/3855

**Comment by loewenstein-sap** [comment]
The whole RFC implementation finally landed. @cloudfoundry/toc We have a [downport pull request on the CLI v8](https://github.com/cloudfoundry/cli/pull/3281) but I don't think we need to keep this tracking issue open.

**Comment by beyhan** [comment]
Thanks for the efforts and the help to track this!
