### ISSUE TITLE
Review ROLES.md

### ISSUE THREAD

**Issue by chipchilders** [cloudfoundry/community#90]
Ensure that the ROLES described include all types of contributions, so that there is room for technical contributions that are not directly tied to code-based contributions. Of note, roles that are requirements for TOC eligibility.

**Comment by emalm** [comment]
We reviewed the contribution language in ROLES.md today for specificity to code and came up with https://github.com/cloudfoundry/community/pull/91 as a first pass to make that scope more inclusive without extensive changes to the existing role descriptions. We also noted that Scribe to WG Execution Lead is a potential pathway for someone to become eligible for election to the TOC without having deep or broad contributions to the project source code.

**Comment by chipchilders** [comment]
closing per meeting

**Comment by jenspinney** [comment]
(Fixed by #91)
