### ISSUE TITLE
ROLES.md Notes section needs a review

### ISSUE THREAD

**Issue by chipchilders** [cloudfoundry/community#96]
Lots of ideas in the Notes section of toc/ROLES.md, but it's not structured well. Consider breaking it up into "fine print rules" and moving some of the general ideas to more appropriate summary sections.

**Comment by AP-Hunt** [comment]
Having read the document, I'm of the belief that it's fine where it is. I don't think that information fits neatly anywhere else in the document, and grouping it together has made it easy to understand. At best we could rename the section "annual leave" and add a second one for disputes.

**Comment by stephanme** [comment]
It could be converted into an RFC similar to [rfc-0008-role-change-process.md](https://github.com/cloudfoundry/community/blob/main/toc/rfc/rfc-0008-role-change-process.md) - just for the manager/lead roles.
But so far we did not see issues with the existing process. Changes are not frequent enough to formalise everything. I'm find with keeping the status quo until we have seen problems.
