### ISSUE TITLE
toc/GOVERNANCE.md needs to go away

### ISSUE THREAD

**Issue by chipchilders** [cloudfoundry/community#97]
Any content in this file that is unique should be placed somewhere else. This file should be gone by the end of the process.

**Comment by AP-Hunt** [comment]
@cloudfoundry/toc Looking over `toc/TOC.md`, `toc/ROLES.md` and `toc/working-groups/*.md`, I don't think there's anything from `toc/GOVERNANCE.md` that isn't covered elsewhere. I'd appreciate a second pair of eyes to confirm that though, before I go ahead and raise a PR to remove the doc.

**Comment by AP-Hunt** [comment]
fixed in #398
