### ISSUE TITLE
Allow members to have access to all CF repos

### ISSUE THREAD

**Issue by ctlong** [cloudfoundry/community#98]
tldr; we're proposing that all CF [Members](https://github.com/cloudfoundry/community/blob/main/toc/ROLES.md#member) be allowed to create and push to (non-main) branches in all CF repositories. This would prevent unnecessary forking, and a given an extra permission layer to members to incentivize joining the community.

### Reduce Forking
Many teams will continue to pair program, and while pair programming it is significantly easier to manage permissions and access via branch than via fork. The pain that we are describing leads to potential contributors creating forks in organizations like cloudfoundry-incubator, which leads to problems as described in this [message](https://lists.cloudfoundry.org/g/cf-dev/topic/7431333?p=,,,20,0,0,0::,,,0,0,0,7431333):

> 1) People that aren't on the project teams have a hard time finding where work of that project team is actually happening.
> 2) The team specific orgs are not typically setup to ensure CLA's for any inbound pull requests.
> 3) Use of the cloudfoundry-incubator for these forks is confusing to observers, and completely different from what the incubator is supposed to be.

### Member Rights
Currently there's not much distinguishing Members from non-Members. We want to empower our Members somewhat in order to incentivize folks to join the community. Creating branches and pushing to repos is a cheap and effective way to make Members feel more like first-class citizens.

#### Protecting the Main Branch
In the past, there was a concern around members with push access pushing to main branches without the buy-in of the project maintainers. In the working group model it is already assumed that the main branches will be protected so that only [Approvers](https://github.com/cloudfoundry/community/blob/main/toc/ROLES.md#approver) have the ability to push and merge PRs to that branch.

#### Branch Cruft
There is a concern that having so many more community members with the ability to create branches will lead to an explosion of new branches on repositories, and that many will become stale and linger around. We think that although this is a concern, the proposed changes are worth that risk.

**Comment by chipchilders** [comment]
This is a super smart idea IMO!

**Comment by ctlong** [comment]
Is this a proposal that will have to wait for the TOC to be elected? What can I do to bring it to the community's attention and potentially get it accepted?

**Comment by mrosecrance** [comment]
I have a few thoughts on this - I'm one of the bosh maintainers for context. We have three patterns of codebase. 
1) Just a master/main branch which we care about (which this pattern seems designed for) 
2) A develop -> main pattern 
3) Multiple prod branches that we care about and patch (stemcell lines being a prime example)

There is a slight risk that the org opens up push permissions without all teams adequately protecting key branches and potentially malicious code slips though and gets published. Considering we're automating publishing of releases on some repos, there may be no human eyes on a chunk of code once it's in a "safe" branch. I think this risk can be mitigated but should be thought through. 

On the branch cruft side, it may be relatively cheap to build out a [github app](https://github.com/probot/) that deletes all stale branches older than a year (or something long)

**Comment by friegger** [comment]
It really lowers the barrier for contributions, for example when contributing as a team, where forked repos need to be made accessibly to others. It would be much cleaner to have a branch in the target repo, which can still be reviewed and merged based on a PR.

Not sure whether GitHub provides such capabilities, but there could be a special branch namespace, like `contrib/*`, which is open to everyone, while all other branches are only accessible for maintainers. This would also reduce the risk to accidentally create new branches that are not protected, but should be.

Another question would be how that interferes with the current CLA process? With the option to directly push to a branch, anybody can add code to the project without anybody else checking. Even though the code of such a branch is not relevant for the release of the project and is not used at all, legally it might still be part of the project and would be an issue?

**Comment by rkoster** [comment]
Like the `contrib/*` convention. This would address the concern around `Multiple prod branches`. This should be relatively save to roll out, just not sure if it is possible allow a team to only create branches which match a wildcard.

Maybe a singed CLA should be added to the [requirements for becoming a Member](https://github.com/cloudfoundry/community/blob/main/toc/ROLES.md#requirements).

**Comment by Benjamintf1** [comment]
Wrt, the logging and metrics repos, I've been trying to push a few things. But one of them that can help is that pr's are limited to approved pull requests and approvals *mostly* seem to go away when new commits are pushed(this is something that's possible easily with concourse, and github settings). If you setup approval requirements, it should be easier to limit potential vulnerabilities, but also rate limit the ability of community prs to consume expensive iaas resources. 

I've also gotten rid of the develop -> master pattern. I don't this is very oss friendly, or in line with where we want to take the org. 

I havn't worked to protect older release branches yet, and that would probably be necessary, but shouldn't be that hard. 

As far as branch cruft, I think @mrosecrance's point is very good in this repsect.

**Comment by emalm** [comment]
I think it'd be interesting to try out this proposal for a small subset of repos in the App Runtime. @ctlong, since you mentioned that this proposal would help out some of your workflows substantially, is there a short list of repos that would be most valuable on which to try this out?

If GitHub doesn't allow branch policies to match a wildcard such as `contrib/*`, another option could be to have canonical contribution forks for repos in the https://github.com/cloudfoundry-community organization, which already has a liberal membership policy.

Also, 👍 to adding CLA acceptance as a membership requirement in the new governance rules. We'll likely want to add some nuance that this may be via a corporate CLA and an individual's association with that corporation. @christopherclark may also be able to tell us what the current state of affairs is with regard to CLAs and members.

**Comment by ctlong** [comment]
@emalm yes! My short list of repos would be:
- [cloundfoundry/routing-release](https://github.com/cloudfoundry/routing-release)
- [cloundfoundry/gorouter](https://github.com/cloudfoundry/gorouter)
- [cloundfoundry/routing-perf-release](https://github.com/cloudfoundry/routing-perf-release)
- [cloundfoundry/cloud_controller_ng](https://github.com/cloudfoundry/cloud_controller_ng)
- [cloundfoundry/capi-release](https://github.com/cloudfoundry/capi-release)

**Comment by emalm** [comment]
Thanks, @ctlong ! Could you coordinate with @christopherclark, @sethboyles, and @ameowlia about how we could arrange an access experiment on those repos? Maybe we could give this proposal a trial for a month to see what problems arise.

**Comment by ctlong** [comment]
Turns out that [base member permissions](https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/setting-base-permissions-for-an-organization) can only be applied at the org-level (not per repo), which doesn't dispose itself well to implementing this proposal on a trial basis. For now, @sethboyles and I created a "[General Contributors team](https://github.com/orgs/cloudfoundry/teams/general-contributors)" with write permissions to cloud_controller_ng and capi-release. We can reuse this team for networking too.

Not yet sure how to batch add all CF members to that team though 🤔 .

**Comment by Benjamintf1** [comment]
I should have updated a vast majority of the logging/metric releases to have:
1) pr rules requiring reviews to run the pipelines
![image](https://user-images.githubusercontent.com/2761008/119868721-a5e0fc80-bedc-11eb-955f-8721368f7c58.png)
![image](https://user-images.githubusercontent.com/2761008/119868798-c01ada80-bedc-11eb-803f-1df91680e7e2.png)
2) only allow pushing from admins
![image](https://user-images.githubusercontent.com/2761008/119868742-ac6f7400-bedc-11eb-9a3a-c21759aece3a.png)

This is the case on both the main branch and the v[0-9]* branches. 

This seems necessary, but I'm not sure if it's sufficient to gain protections. Anyone know if there's anything I should be concerned about?

**Comment by Benjamintf1** [comment]
update: I think I want to ensure that approvals are limited before making these changes in logging and metric repos and that's not done.

**Comment by ctlong** [comment]
> update: I think I want to ensure that approvals are limited before making these changes in logging and metric repos and that's not done.

@Benjamintf1 can you elaborate on the problem? Is it that you want to limit approvals to only specific repo members (ie. admins)?

**Comment by Benjamintf1** [comment]
Reading the settings, it seems like pr approvals are allowed to anyone with write permissions. This seems less then ideal/like it would make any branch permissions null/pointless.

**Comment by ctlong** [comment]
That's not ideal. I don't think that makes branch permissions pointless though, as the restriction on who can push to matching branches also prevents anyone without those permissions from merging PRs into those branches. @sethboyles and I tested that.

**Comment by ctlong** [comment]
@Benjamintf1 after you pointed out the extra permissions attached to write access I did some more research and it turns out that there's a lot more permissions attached to it that we might not want to give, for example:
* Close, reopen, and assign all issues and pull requests
* Edit and delete anyone's comments on commits, pull requests, and issues
* Create and edit releases
* Create, edit, run, re-run, and cancel GitHub Actions workflows

(See the Github org roles and their repository permission levels [here](https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-permission-levels-for-an-organization))
​
@ameowlia and @sethboyles also pointed out the following:
​
> Based on the [proposed community roles](https://github.com/cloudfoundry/community/blob/main/toc/ROLES.md#member) there are the following roles per working group:
> 1. Member
> 1. Approver - has write permissions to repos (presumably to all branches), can allow PRs to be merged.
> 1. Leads - can manipulate issues/PRs
> 
> Giving write permissions to members are incongruent with those proposed roles. There might be space to edit the proposed roles, but it does seem like we would be forced to open up more permissions than we would like to. Not sure who came up with the proposed roles, but maybe they have thoughts on how the general intent of your proposal can be integrated with the Working Group model?

It doesn't fit perfectly (ex: approvers would be able to manipulate issues/PRs), but the following seemed the most logical current mapping for the proposed community roles based on their descriptions:
1. Member -> Read access
2. Approver -> Write access
3. Leads -> Admin access

@chipchilders @emalm does that look right? _If_ that is the case, should the roles doc be amended to include that information?

As for this specific proposal, it essentially proposes changing the mapping to:
1. Member -> Write access (w/o access to protected branches)
2. Approver -> Write access (w/ access to protected branches)
3. Leads -> Admin access

That change doesn't sound as optimal to me as I previously believed it to be. What do folks think? It may be worth waiting for Github to release new RBAC features for Github Enterprises, which is planned for relatively soon: https://github.com/github/roadmap/issues/111 (it's been pushed back several times already though).

**Comment by loewenstein** [comment]
Would a `cloudfoundry-contributions` org with relaxed permissions, like member -> write access, be able to get us 80% to where we want to be?

I.e. no need for personal forks, it's clear where contributions happen, members have slightly privileged access.

WDYT?

**Comment by Benjamintf1** [comment]
I feel like once you have to work on a fork, it's not any more or less convenient for that to be a personal fork(or a org fork for a group of people) then any other org/repository.

**Comment by AP-Hunt** [comment]
The TOC discussed this on 30th August 2022, along with @ctlong. In summary, we don't feel that GitHub's authorisation model is sufficiently granular for us to implement this safely. There's nothing on the horizon that would enable it either, so we feel this has hit a dead end, and we're closing it off.
