### ISSUE TITLE
[Terraform-Provider-Cloudfoundry]: Request to add sonar checks through sonarcloud

### ISSUE THREAD

**Issue by vipinvkmenon** [cloudfoundry/community#999]
As a best practice for Code Quality, we must integrate Sonar chacks into the repository.
I can see that certain projects from the cloudfoundry organisation have already been [added](https://sonarcloud.io/organizations/cloudfoundry/projects). 

Only the org administrators could list/add projects to the sonarcloud.

Method to add the repo: https://docs.sonarsource.com/sonarcloud/getting-started/github/

After the repository is added we will need the following properties:
sonar.organization=
sonar.projectKey=
sonar.projectName=

Which can be provided in this ticket or be added as a PR to the sonarcloud properties file in the [repo](https://github.com/cloudfoundry/terraform-provider-cloudfoundry/blob/ad2214ef7c7e37b0c5409cbd3574aeb9dc36a10d/sonar-project.properties#L1-L3)

**Comment by vipinvkmenon** [comment]
That should be fine Beyhan

**Comment by beyhan** [comment]
Unfortunately, we had to postpone this to the next TOC meeting. If this is urgent I can try to resolve this async. Please let me know.

**Comment by beyhan** [comment]
@vipinvkmenon you will get help from @stephanme

**Comment by stephanme** [comment]
I added [terraform-provider-cloudfoundry](https://github.com/cloudfoundry/terraform-provider-cloudfoundry) to SonarCloud and added the resulting SONAR_TOKEN as a repository secret to the repo.

SonarCloud Project Info: [https://sonarcloud.io/project/information?id=cloudfoundry_terraform-provider-cloudfoundry]
Project Key: cloudfoundry_terraform-provider-cloudfoundry
Organization Key: cloudfoundry

Ping me, in case additional configuration is needed that can only be done as admin.

**Comment by vipinvkmenon** [comment]
The SonarClud Check works perfectly :)
Thanks for all the support. The ticket can be closed now :)
